AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Documentation:
  Enabled: false
